# Generated by Django 6.0 on 2026-01-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bem_categoria_bem_valor_estimado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bem',
            options={'verbose_name': 'Bem', 'verbose_name_plural': 'Bens'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
